/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesIdRouteImport } from './routes/resources/$id'
import { Route as ResourcesCreateRouteImport } from './routes/resources/create'
import { Route as ResourcesEditIdRouteImport } from './routes/resources/edit/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIdRoute = ResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCreateRoute = ResourcesCreateRouteImport.update({
  id: '/resources/create',
  path: '/resources/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesEditIdRoute = ResourcesEditIdRouteImport.update({
  id: '/resources/edit/$id',
  path: '/resources/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sandbox': typeof SandboxRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/resources/create': typeof ResourcesCreateRoute
  '/resources/': typeof ResourcesIndexRoute
  '/resources/edit/$id': typeof ResourcesEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sandbox': typeof SandboxRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/resources/create': typeof ResourcesCreateRoute
  '/resources': typeof ResourcesIndexRoute
  '/resources/edit/$id': typeof ResourcesEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sandbox': typeof SandboxRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/resources/create': typeof ResourcesCreateRoute
  '/resources/': typeof ResourcesIndexRoute
  '/resources/edit/$id': typeof ResourcesEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sandbox'
    | '/resources/$id'
    | '/resources/create'
    | '/resources/'
    | '/resources/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sandbox'
    | '/resources/$id'
    | '/resources/create'
    | '/resources'
    | '/resources/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/sandbox'
    | '/resources/$id'
    | '/resources/create'
    | '/resources/'
    | '/resources/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SandboxRoute: typeof SandboxRoute
  ResourcesIdRoute: typeof ResourcesIdRoute
  ResourcesCreateRoute: typeof ResourcesCreateRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ResourcesEditIdRoute: typeof ResourcesEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$id': {
      id: '/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof ResourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/create': {
      id: '/resources/create'
      path: '/resources/create'
      fullPath: '/resources/create'
      preLoaderRoute: typeof ResourcesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/edit/$id': {
      id: '/resources/edit/$id'
      path: '/resources/edit/$id'
      fullPath: '/resources/edit/$id'
      preLoaderRoute: typeof ResourcesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SandboxRoute: SandboxRoute,
  ResourcesIdRoute: ResourcesIdRoute,
  ResourcesCreateRoute: ResourcesCreateRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ResourcesEditIdRoute: ResourcesEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
