/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppSandboxRouteImport } from './routes/_app/sandbox'
import { Route as ContractsBatchPrintRouteImport } from './routes/contracts/batch-print'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminReservationsRouteImport } from './routes/_app/admin/reservations'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppCollectionsIndexRouteImport } from './routes/_app/collections/index'
import { Route as AppCollectionsIdRouteImport } from './routes/_app/collections/$id'
import { Route as AppCollectionsCreateRouteImport } from './routes/_app/collections/create'
import { Route as AppContractsIndexRouteImport } from './routes/_app/contracts/index'
import { Route as AppReservationsIndexRouteImport } from './routes/_app/reservations/index'
import { Route as AppReservationsIdRouteImport } from './routes/_app/reservations/$id'
import { Route as AppReservationsCreateRouteImport } from './routes/_app/reservations/create'
import { Route as AppResourcesIndexRouteImport } from './routes/_app/resources/index'
import { Route as AppResourcesIdRouteImport } from './routes/_app/resources/$id'
import { Route as AppResourcesCreateRouteImport } from './routes/_app/resources/create'
import { Route as AppRestrictionsIndexRouteImport } from './routes/_app/restrictions/index'
import { Route as AppRestrictionsIdRouteImport } from './routes/_app/restrictions/$id'
import { Route as AppRestrictionsCreateRouteImport } from './routes/_app/restrictions/create'
import { Route as AppStatsIndexRouteImport } from './routes/_app/stats/index'
import { Route as AppAdminDashboardIndexRouteImport } from './routes/_app/admin/dashboard/index'
import { Route as AppAdminGroupsIndexRouteImport } from './routes/_app/admin/groups/index'
import { Route as AppAdminGroupsIdRouteImport } from './routes/_app/admin/groups/$id'
import { Route as AppAdminGroupsCreateRouteImport } from './routes/_app/admin/groups/create'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminUsersIdRouteImport } from './routes/_app/admin/users/$id'
import { Route as AppAdminUsersBatchRegisterRouteImport } from './routes/_app/admin/users/batch-register'
import { Route as AppAdminUsersCreateRouteImport } from './routes/_app/admin/users/create'
import { Route as AppCollectionsEditIdRouteImport } from './routes/_app/collections/edit.$id'
import { Route as AppReservationsEditIdRouteImport } from './routes/_app/reservations/edit.$id'
import { Route as AppResourcesEditIdRouteImport } from './routes/_app/resources/edit/$id'
import { Route as AppRestrictionsEditIdRouteImport } from './routes/_app/restrictions/edit.$id'
import { Route as AppAdminGroupsEditIdRouteImport } from './routes/_app/admin/groups/edit.$id'
import { Route as AppAdminUsersEditIdRouteImport } from './routes/_app/admin/users/edit.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxRoute = AppSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AppRoute,
} as any)
const ContractsBatchPrintRoute = ContractsBatchPrintRouteImport.update({
  id: '/contracts/batch-print',
  path: '/contracts/batch-print',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReservationsRoute = AppAdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsIndexRoute = AppCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsIdRoute = AppCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsCreateRoute = AppCollectionsCreateRouteImport.update({
  id: '/collections/create',
  path: '/collections/create',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsIndexRoute = AppContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsIndexRoute = AppReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsIdRoute = AppReservationsIdRouteImport.update({
  id: '/reservations/$id',
  path: '/reservations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsCreateRoute = AppReservationsCreateRouteImport.update({
  id: '/reservations/create',
  path: '/reservations/create',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesIndexRoute = AppResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesIdRoute = AppResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesCreateRoute = AppResourcesCreateRouteImport.update({
  id: '/resources/create',
  path: '/resources/create',
  getParentRoute: () => AppRoute,
} as any)
const AppRestrictionsIndexRoute = AppRestrictionsIndexRouteImport.update({
  id: '/restrictions/',
  path: '/restrictions/',
  getParentRoute: () => AppRoute,
} as any)
const AppRestrictionsIdRoute = AppRestrictionsIdRouteImport.update({
  id: '/restrictions/$id',
  path: '/restrictions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRestrictionsCreateRoute = AppRestrictionsCreateRouteImport.update({
  id: '/restrictions/create',
  path: '/restrictions/create',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsIndexRoute = AppStatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardIndexRoute = AppAdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGroupsIndexRoute = AppAdminGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGroupsIdRoute = AppAdminGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGroupsCreateRoute = AppAdminGroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersIdRoute = AppAdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersBatchRegisterRoute =
  AppAdminUsersBatchRegisterRouteImport.update({
    id: '/users/batch-register',
    path: '/users/batch-register',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminUsersCreateRoute = AppAdminUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppCollectionsEditIdRoute = AppCollectionsEditIdRouteImport.update({
  id: '/collections/edit/$id',
  path: '/collections/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsEditIdRoute = AppReservationsEditIdRouteImport.update({
  id: '/reservations/edit/$id',
  path: '/reservations/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesEditIdRoute = AppResourcesEditIdRouteImport.update({
  id: '/resources/edit/$id',
  path: '/resources/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRestrictionsEditIdRoute = AppRestrictionsEditIdRouteImport.update({
  id: '/restrictions/edit/$id',
  path: '/restrictions/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminGroupsEditIdRoute = AppAdminGroupsEditIdRouteImport.update({
  id: '/groups/edit/$id',
  path: '/groups/edit/$id',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersEditIdRoute = AppAdminUsersEditIdRouteImport.update({
  id: '/users/edit/$id',
  path: '/users/edit/$id',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/sandbox': typeof AppSandboxRoute
  '/contracts/batch-print': typeof ContractsBatchPrintRoute
  '/admin/reservations': typeof AppAdminReservationsRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/collections/create': typeof AppCollectionsCreateRoute
  '/reservations/$id': typeof AppReservationsIdRoute
  '/reservations/create': typeof AppReservationsCreateRoute
  '/resources/$id': typeof AppResourcesIdRoute
  '/resources/create': typeof AppResourcesCreateRoute
  '/restrictions/$id': typeof AppRestrictionsIdRoute
  '/restrictions/create': typeof AppRestrictionsCreateRoute
  '/admin/': typeof AppAdminIndexRoute
  '/calendar/': typeof AppCalendarIndexRoute
  '/collections/': typeof AppCollectionsIndexRoute
  '/contracts/': typeof AppContractsIndexRoute
  '/reservations/': typeof AppReservationsIndexRoute
  '/resources/': typeof AppResourcesIndexRoute
  '/restrictions/': typeof AppRestrictionsIndexRoute
  '/stats/': typeof AppStatsIndexRoute
  '/admin/groups/$id': typeof AppAdminGroupsIdRoute
  '/admin/groups/create': typeof AppAdminGroupsCreateRoute
  '/admin/users/$id': typeof AppAdminUsersIdRoute
  '/admin/users/batch-register': typeof AppAdminUsersBatchRegisterRoute
  '/admin/users/create': typeof AppAdminUsersCreateRoute
  '/collections/edit/$id': typeof AppCollectionsEditIdRoute
  '/reservations/edit/$id': typeof AppReservationsEditIdRoute
  '/resources/edit/$id': typeof AppResourcesEditIdRoute
  '/restrictions/edit/$id': typeof AppRestrictionsEditIdRoute
  '/admin/dashboard/': typeof AppAdminDashboardIndexRoute
  '/admin/groups/': typeof AppAdminGroupsIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/admin/groups/edit/$id': typeof AppAdminGroupsEditIdRoute
  '/admin/users/edit/$id': typeof AppAdminUsersEditIdRoute
}
export interface FileRoutesByTo {
  '/sandbox': typeof AppSandboxRoute
  '/contracts/batch-print': typeof ContractsBatchPrintRoute
  '/': typeof AppIndexRoute
  '/admin/reservations': typeof AppAdminReservationsRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/collections/create': typeof AppCollectionsCreateRoute
  '/reservations/$id': typeof AppReservationsIdRoute
  '/reservations/create': typeof AppReservationsCreateRoute
  '/resources/$id': typeof AppResourcesIdRoute
  '/resources/create': typeof AppResourcesCreateRoute
  '/restrictions/$id': typeof AppRestrictionsIdRoute
  '/restrictions/create': typeof AppRestrictionsCreateRoute
  '/admin': typeof AppAdminIndexRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/collections': typeof AppCollectionsIndexRoute
  '/contracts': typeof AppContractsIndexRoute
  '/reservations': typeof AppReservationsIndexRoute
  '/resources': typeof AppResourcesIndexRoute
  '/restrictions': typeof AppRestrictionsIndexRoute
  '/stats': typeof AppStatsIndexRoute
  '/admin/groups/$id': typeof AppAdminGroupsIdRoute
  '/admin/groups/create': typeof AppAdminGroupsCreateRoute
  '/admin/users/$id': typeof AppAdminUsersIdRoute
  '/admin/users/batch-register': typeof AppAdminUsersBatchRegisterRoute
  '/admin/users/create': typeof AppAdminUsersCreateRoute
  '/collections/edit/$id': typeof AppCollectionsEditIdRoute
  '/reservations/edit/$id': typeof AppReservationsEditIdRoute
  '/resources/edit/$id': typeof AppResourcesEditIdRoute
  '/restrictions/edit/$id': typeof AppRestrictionsEditIdRoute
  '/admin/dashboard': typeof AppAdminDashboardIndexRoute
  '/admin/groups': typeof AppAdminGroupsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/admin/groups/edit/$id': typeof AppAdminGroupsEditIdRoute
  '/admin/users/edit/$id': typeof AppAdminUsersEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/sandbox': typeof AppSandboxRoute
  '/contracts/batch-print': typeof ContractsBatchPrintRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/reservations': typeof AppAdminReservationsRoute
  '/_app/collections/$id': typeof AppCollectionsIdRoute
  '/_app/collections/create': typeof AppCollectionsCreateRoute
  '/_app/reservations/$id': typeof AppReservationsIdRoute
  '/_app/reservations/create': typeof AppReservationsCreateRoute
  '/_app/resources/$id': typeof AppResourcesIdRoute
  '/_app/resources/create': typeof AppResourcesCreateRoute
  '/_app/restrictions/$id': typeof AppRestrictionsIdRoute
  '/_app/restrictions/create': typeof AppRestrictionsCreateRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_app/collections/': typeof AppCollectionsIndexRoute
  '/_app/contracts/': typeof AppContractsIndexRoute
  '/_app/reservations/': typeof AppReservationsIndexRoute
  '/_app/resources/': typeof AppResourcesIndexRoute
  '/_app/restrictions/': typeof AppRestrictionsIndexRoute
  '/_app/stats/': typeof AppStatsIndexRoute
  '/_app/admin/groups/$id': typeof AppAdminGroupsIdRoute
  '/_app/admin/groups/create': typeof AppAdminGroupsCreateRoute
  '/_app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/_app/admin/users/batch-register': typeof AppAdminUsersBatchRegisterRoute
  '/_app/admin/users/create': typeof AppAdminUsersCreateRoute
  '/_app/collections/edit/$id': typeof AppCollectionsEditIdRoute
  '/_app/reservations/edit/$id': typeof AppReservationsEditIdRoute
  '/_app/resources/edit/$id': typeof AppResourcesEditIdRoute
  '/_app/restrictions/edit/$id': typeof AppRestrictionsEditIdRoute
  '/_app/admin/dashboard/': typeof AppAdminDashboardIndexRoute
  '/_app/admin/groups/': typeof AppAdminGroupsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/admin/groups/edit/$id': typeof AppAdminGroupsEditIdRoute
  '/_app/admin/users/edit/$id': typeof AppAdminUsersEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sandbox'
    | '/contracts/batch-print'
    | '/admin/reservations'
    | '/collections/$id'
    | '/collections/create'
    | '/reservations/$id'
    | '/reservations/create'
    | '/resources/$id'
    | '/resources/create'
    | '/restrictions/$id'
    | '/restrictions/create'
    | '/admin/'
    | '/calendar/'
    | '/collections/'
    | '/contracts/'
    | '/reservations/'
    | '/resources/'
    | '/restrictions/'
    | '/stats/'
    | '/admin/groups/$id'
    | '/admin/groups/create'
    | '/admin/users/$id'
    | '/admin/users/batch-register'
    | '/admin/users/create'
    | '/collections/edit/$id'
    | '/reservations/edit/$id'
    | '/resources/edit/$id'
    | '/restrictions/edit/$id'
    | '/admin/dashboard/'
    | '/admin/groups/'
    | '/admin/users/'
    | '/admin/groups/edit/$id'
    | '/admin/users/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sandbox'
    | '/contracts/batch-print'
    | '/'
    | '/admin/reservations'
    | '/collections/$id'
    | '/collections/create'
    | '/reservations/$id'
    | '/reservations/create'
    | '/resources/$id'
    | '/resources/create'
    | '/restrictions/$id'
    | '/restrictions/create'
    | '/admin'
    | '/calendar'
    | '/collections'
    | '/contracts'
    | '/reservations'
    | '/resources'
    | '/restrictions'
    | '/stats'
    | '/admin/groups/$id'
    | '/admin/groups/create'
    | '/admin/users/$id'
    | '/admin/users/batch-register'
    | '/admin/users/create'
    | '/collections/edit/$id'
    | '/reservations/edit/$id'
    | '/resources/edit/$id'
    | '/restrictions/edit/$id'
    | '/admin/dashboard'
    | '/admin/groups'
    | '/admin/users'
    | '/admin/groups/edit/$id'
    | '/admin/users/edit/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/admin'
    | '/_app/sandbox'
    | '/contracts/batch-print'
    | '/_app/'
    | '/_app/admin/reservations'
    | '/_app/collections/$id'
    | '/_app/collections/create'
    | '/_app/reservations/$id'
    | '/_app/reservations/create'
    | '/_app/resources/$id'
    | '/_app/resources/create'
    | '/_app/restrictions/$id'
    | '/_app/restrictions/create'
    | '/_app/admin/'
    | '/_app/calendar/'
    | '/_app/collections/'
    | '/_app/contracts/'
    | '/_app/reservations/'
    | '/_app/resources/'
    | '/_app/restrictions/'
    | '/_app/stats/'
    | '/_app/admin/groups/$id'
    | '/_app/admin/groups/create'
    | '/_app/admin/users/$id'
    | '/_app/admin/users/batch-register'
    | '/_app/admin/users/create'
    | '/_app/collections/edit/$id'
    | '/_app/reservations/edit/$id'
    | '/_app/resources/edit/$id'
    | '/_app/restrictions/edit/$id'
    | '/_app/admin/dashboard/'
    | '/_app/admin/groups/'
    | '/_app/admin/users/'
    | '/_app/admin/groups/edit/$id'
    | '/_app/admin/users/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ContractsBatchPrintRoute: typeof ContractsBatchPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sandbox': {
      id: '/_app/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof AppSandboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/contracts/batch-print': {
      id: '/contracts/batch-print'
      path: '/contracts/batch-print'
      fullPath: '/contracts/batch-print'
      preLoaderRoute: typeof ContractsBatchPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/reservations': {
      id: '/_app/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AppAdminReservationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections/': {
      id: '/_app/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AppCollectionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections/$id': {
      id: '/_app/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AppCollectionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections/create': {
      id: '/_app/collections/create'
      path: '/collections/create'
      fullPath: '/collections/create'
      preLoaderRoute: typeof AppCollectionsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/': {
      id: '/_app/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AppContractsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations/': {
      id: '/_app/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof AppReservationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations/$id': {
      id: '/_app/reservations/$id'
      path: '/reservations/$id'
      fullPath: '/reservations/$id'
      preLoaderRoute: typeof AppReservationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations/create': {
      id: '/_app/reservations/create'
      path: '/reservations/create'
      fullPath: '/reservations/create'
      preLoaderRoute: typeof AppReservationsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/': {
      id: '/_app/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof AppResourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/$id': {
      id: '/_app/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof AppResourcesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/create': {
      id: '/_app/resources/create'
      path: '/resources/create'
      fullPath: '/resources/create'
      preLoaderRoute: typeof AppResourcesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restrictions/': {
      id: '/_app/restrictions/'
      path: '/restrictions'
      fullPath: '/restrictions/'
      preLoaderRoute: typeof AppRestrictionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restrictions/$id': {
      id: '/_app/restrictions/$id'
      path: '/restrictions/$id'
      fullPath: '/restrictions/$id'
      preLoaderRoute: typeof AppRestrictionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restrictions/create': {
      id: '/_app/restrictions/create'
      path: '/restrictions/create'
      fullPath: '/restrictions/create'
      preLoaderRoute: typeof AppRestrictionsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats/': {
      id: '/_app/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof AppStatsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard/': {
      id: '/_app/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AppAdminDashboardIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/groups/': {
      id: '/_app/admin/groups/'
      path: '/groups'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AppAdminGroupsIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/groups/$id': {
      id: '/_app/admin/groups/$id'
      path: '/groups/$id'
      fullPath: '/admin/groups/$id'
      preLoaderRoute: typeof AppAdminGroupsIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/groups/create': {
      id: '/_app/admin/groups/create'
      path: '/groups/create'
      fullPath: '/admin/groups/create'
      preLoaderRoute: typeof AppAdminGroupsCreateRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users/$id': {
      id: '/_app/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AppAdminUsersIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users/batch-register': {
      id: '/_app/admin/users/batch-register'
      path: '/users/batch-register'
      fullPath: '/admin/users/batch-register'
      preLoaderRoute: typeof AppAdminUsersBatchRegisterRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users/create': {
      id: '/_app/admin/users/create'
      path: '/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AppAdminUsersCreateRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/collections/edit/$id': {
      id: '/_app/collections/edit/$id'
      path: '/collections/edit/$id'
      fullPath: '/collections/edit/$id'
      preLoaderRoute: typeof AppCollectionsEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations/edit/$id': {
      id: '/_app/reservations/edit/$id'
      path: '/reservations/edit/$id'
      fullPath: '/reservations/edit/$id'
      preLoaderRoute: typeof AppReservationsEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/edit/$id': {
      id: '/_app/resources/edit/$id'
      path: '/resources/edit/$id'
      fullPath: '/resources/edit/$id'
      preLoaderRoute: typeof AppResourcesEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restrictions/edit/$id': {
      id: '/_app/restrictions/edit/$id'
      path: '/restrictions/edit/$id'
      fullPath: '/restrictions/edit/$id'
      preLoaderRoute: typeof AppRestrictionsEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/groups/edit/$id': {
      id: '/_app/admin/groups/edit/$id'
      path: '/groups/edit/$id'
      fullPath: '/admin/groups/edit/$id'
      preLoaderRoute: typeof AppAdminGroupsEditIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users/edit/$id': {
      id: '/_app/admin/users/edit/$id'
      path: '/users/edit/$id'
      fullPath: '/admin/users/edit/$id'
      preLoaderRoute: typeof AppAdminUsersEditIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminReservationsRoute: typeof AppAdminReservationsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminGroupsIdRoute: typeof AppAdminGroupsIdRoute
  AppAdminGroupsCreateRoute: typeof AppAdminGroupsCreateRoute
  AppAdminUsersIdRoute: typeof AppAdminUsersIdRoute
  AppAdminUsersBatchRegisterRoute: typeof AppAdminUsersBatchRegisterRoute
  AppAdminUsersCreateRoute: typeof AppAdminUsersCreateRoute
  AppAdminDashboardIndexRoute: typeof AppAdminDashboardIndexRoute
  AppAdminGroupsIndexRoute: typeof AppAdminGroupsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppAdminGroupsEditIdRoute: typeof AppAdminGroupsEditIdRoute
  AppAdminUsersEditIdRoute: typeof AppAdminUsersEditIdRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminReservationsRoute: AppAdminReservationsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminGroupsIdRoute: AppAdminGroupsIdRoute,
  AppAdminGroupsCreateRoute: AppAdminGroupsCreateRoute,
  AppAdminUsersIdRoute: AppAdminUsersIdRoute,
  AppAdminUsersBatchRegisterRoute: AppAdminUsersBatchRegisterRoute,
  AppAdminUsersCreateRoute: AppAdminUsersCreateRoute,
  AppAdminDashboardIndexRoute: AppAdminDashboardIndexRoute,
  AppAdminGroupsIndexRoute: AppAdminGroupsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppAdminGroupsEditIdRoute: AppAdminGroupsEditIdRoute,
  AppAdminUsersEditIdRoute: AppAdminUsersEditIdRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppSandboxRoute: typeof AppSandboxRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCollectionsIdRoute: typeof AppCollectionsIdRoute
  AppCollectionsCreateRoute: typeof AppCollectionsCreateRoute
  AppReservationsIdRoute: typeof AppReservationsIdRoute
  AppReservationsCreateRoute: typeof AppReservationsCreateRoute
  AppResourcesIdRoute: typeof AppResourcesIdRoute
  AppResourcesCreateRoute: typeof AppResourcesCreateRoute
  AppRestrictionsIdRoute: typeof AppRestrictionsIdRoute
  AppRestrictionsCreateRoute: typeof AppRestrictionsCreateRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppCollectionsIndexRoute: typeof AppCollectionsIndexRoute
  AppContractsIndexRoute: typeof AppContractsIndexRoute
  AppReservationsIndexRoute: typeof AppReservationsIndexRoute
  AppResourcesIndexRoute: typeof AppResourcesIndexRoute
  AppRestrictionsIndexRoute: typeof AppRestrictionsIndexRoute
  AppStatsIndexRoute: typeof AppStatsIndexRoute
  AppCollectionsEditIdRoute: typeof AppCollectionsEditIdRoute
  AppReservationsEditIdRoute: typeof AppReservationsEditIdRoute
  AppResourcesEditIdRoute: typeof AppResourcesEditIdRoute
  AppRestrictionsEditIdRoute: typeof AppRestrictionsEditIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppSandboxRoute: AppSandboxRoute,
  AppIndexRoute: AppIndexRoute,
  AppCollectionsIdRoute: AppCollectionsIdRoute,
  AppCollectionsCreateRoute: AppCollectionsCreateRoute,
  AppReservationsIdRoute: AppReservationsIdRoute,
  AppReservationsCreateRoute: AppReservationsCreateRoute,
  AppResourcesIdRoute: AppResourcesIdRoute,
  AppResourcesCreateRoute: AppResourcesCreateRoute,
  AppRestrictionsIdRoute: AppRestrictionsIdRoute,
  AppRestrictionsCreateRoute: AppRestrictionsCreateRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppCollectionsIndexRoute: AppCollectionsIndexRoute,
  AppContractsIndexRoute: AppContractsIndexRoute,
  AppReservationsIndexRoute: AppReservationsIndexRoute,
  AppResourcesIndexRoute: AppResourcesIndexRoute,
  AppRestrictionsIndexRoute: AppRestrictionsIndexRoute,
  AppStatsIndexRoute: AppStatsIndexRoute,
  AppCollectionsEditIdRoute: AppCollectionsEditIdRoute,
  AppReservationsEditIdRoute: AppReservationsEditIdRoute,
  AppResourcesEditIdRoute: AppResourcesEditIdRoute,
  AppRestrictionsEditIdRoute: AppRestrictionsEditIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ContractsBatchPrintRoute: ContractsBatchPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
