/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSandboxRouteImport } from './routes/_app/sandbox'
import { Route as ContractsIndexRouteImport } from './routes/contracts/index'
import { Route as ContractsBatchPrintRouteImport } from './routes/contracts/batch-print'
import { Route as AppAdminDashboardRouteImport } from './routes/_app/admin/dashboard'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppCollectionsIndexRouteImport } from './routes/_app/collections/index'
import { Route as AppCollectionsIdRouteImport } from './routes/_app/collections/$id'
import { Route as AppCollectionsCreateRouteImport } from './routes/_app/collections/create'
import { Route as AppGroupsIndexRouteImport } from './routes/_app/groups/index'
import { Route as AppGroupsIdRouteImport } from './routes/_app/groups/$id'
import { Route as AppGroupsCreateRouteImport } from './routes/_app/groups/create'
import { Route as AppReservationsIndexRouteImport } from './routes/_app/reservations/index'
import { Route as AppReservationsIdRouteImport } from './routes/_app/reservations/$id'
import { Route as AppReservationsCreateRouteImport } from './routes/_app/reservations/create'
import { Route as AppResourcesIndexRouteImport } from './routes/_app/resources/index'
import { Route as AppResourcesIdRouteImport } from './routes/_app/resources/$id'
import { Route as AppResourcesCreateRouteImport } from './routes/_app/resources/create'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppUsersIdRouteImport } from './routes/_app/users/$id'
import { Route as AppUsersCreateRouteImport } from './routes/_app/users/create'
import { Route as AppCollectionsEditIdRouteImport } from './routes/_app/collections/edit.$id'
import { Route as AppGroupsEditIdRouteImport } from './routes/_app/groups/edit.$id'
import { Route as AppReservationsEditIdRouteImport } from './routes/_app/reservations/edit.$id'
import { Route as AppResourcesEditIdRouteImport } from './routes/_app/resources/edit/$id'
import { Route as AppUsersEditIdRouteImport } from './routes/_app/users/edit.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxRoute = AppSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AppRoute,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsBatchPrintRoute = ContractsBatchPrintRouteImport.update({
  id: '/contracts/batch-print',
  path: '/contracts/batch-print',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsIndexRoute = AppCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsIdRoute = AppCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsCreateRoute = AppCollectionsCreateRouteImport.update({
  id: '/collections/create',
  path: '/collections/create',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIdRoute = AppGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsCreateRoute = AppGroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsIndexRoute = AppReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsIdRoute = AppReservationsIdRouteImport.update({
  id: '/reservations/$id',
  path: '/reservations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsCreateRoute = AppReservationsCreateRouteImport.update({
  id: '/reservations/create',
  path: '/reservations/create',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesIndexRoute = AppResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesIdRoute = AppResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesCreateRoute = AppResourcesCreateRouteImport.update({
  id: '/resources/create',
  path: '/resources/create',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIdRoute = AppUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersCreateRoute = AppUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsEditIdRoute = AppCollectionsEditIdRouteImport.update({
  id: '/collections/edit/$id',
  path: '/collections/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsEditIdRoute = AppGroupsEditIdRouteImport.update({
  id: '/groups/edit/$id',
  path: '/groups/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsEditIdRoute = AppReservationsEditIdRouteImport.update({
  id: '/reservations/edit/$id',
  path: '/reservations/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesEditIdRoute = AppResourcesEditIdRouteImport.update({
  id: '/resources/edit/$id',
  path: '/resources/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersEditIdRoute = AppUsersEditIdRouteImport.update({
  id: '/users/edit/$id',
  path: '/users/edit/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sandbox': typeof AppSandboxRoute
  '/contracts/batch-print': typeof ContractsBatchPrintRoute
  '/contracts/': typeof ContractsIndexRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/collections/create': typeof AppCollectionsCreateRoute
  '/groups/$id': typeof AppGroupsIdRoute
  '/groups/create': typeof AppGroupsCreateRoute
  '/reservations/$id': typeof AppReservationsIdRoute
  '/reservations/create': typeof AppReservationsCreateRoute
  '/resources/$id': typeof AppResourcesIdRoute
  '/resources/create': typeof AppResourcesCreateRoute
  '/users/$id': typeof AppUsersIdRoute
  '/users/create': typeof AppUsersCreateRoute
  '/calendar/': typeof AppCalendarIndexRoute
  '/collections/': typeof AppCollectionsIndexRoute
  '/groups/': typeof AppGroupsIndexRoute
  '/reservations/': typeof AppReservationsIndexRoute
  '/resources/': typeof AppResourcesIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/collections/edit/$id': typeof AppCollectionsEditIdRoute
  '/groups/edit/$id': typeof AppGroupsEditIdRoute
  '/reservations/edit/$id': typeof AppReservationsEditIdRoute
  '/resources/edit/$id': typeof AppResourcesEditIdRoute
  '/users/edit/$id': typeof AppUsersEditIdRoute
}
export interface FileRoutesByTo {
  '/sandbox': typeof AppSandboxRoute
  '/contracts/batch-print': typeof ContractsBatchPrintRoute
  '/': typeof AppIndexRoute
  '/contracts': typeof ContractsIndexRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/collections/create': typeof AppCollectionsCreateRoute
  '/groups/$id': typeof AppGroupsIdRoute
  '/groups/create': typeof AppGroupsCreateRoute
  '/reservations/$id': typeof AppReservationsIdRoute
  '/reservations/create': typeof AppReservationsCreateRoute
  '/resources/$id': typeof AppResourcesIdRoute
  '/resources/create': typeof AppResourcesCreateRoute
  '/users/$id': typeof AppUsersIdRoute
  '/users/create': typeof AppUsersCreateRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/collections': typeof AppCollectionsIndexRoute
  '/groups': typeof AppGroupsIndexRoute
  '/reservations': typeof AppReservationsIndexRoute
  '/resources': typeof AppResourcesIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/collections/edit/$id': typeof AppCollectionsEditIdRoute
  '/groups/edit/$id': typeof AppGroupsEditIdRoute
  '/reservations/edit/$id': typeof AppReservationsEditIdRoute
  '/resources/edit/$id': typeof AppResourcesEditIdRoute
  '/users/edit/$id': typeof AppUsersEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/sandbox': typeof AppSandboxRoute
  '/contracts/batch-print': typeof ContractsBatchPrintRoute
  '/_app/': typeof AppIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/collections/$id': typeof AppCollectionsIdRoute
  '/_app/collections/create': typeof AppCollectionsCreateRoute
  '/_app/groups/$id': typeof AppGroupsIdRoute
  '/_app/groups/create': typeof AppGroupsCreateRoute
  '/_app/reservations/$id': typeof AppReservationsIdRoute
  '/_app/reservations/create': typeof AppReservationsCreateRoute
  '/_app/resources/$id': typeof AppResourcesIdRoute
  '/_app/resources/create': typeof AppResourcesCreateRoute
  '/_app/users/$id': typeof AppUsersIdRoute
  '/_app/users/create': typeof AppUsersCreateRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_app/collections/': typeof AppCollectionsIndexRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_app/reservations/': typeof AppReservationsIndexRoute
  '/_app/resources/': typeof AppResourcesIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/collections/edit/$id': typeof AppCollectionsEditIdRoute
  '/_app/groups/edit/$id': typeof AppGroupsEditIdRoute
  '/_app/reservations/edit/$id': typeof AppReservationsEditIdRoute
  '/_app/resources/edit/$id': typeof AppResourcesEditIdRoute
  '/_app/users/edit/$id': typeof AppUsersEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sandbox'
    | '/contracts/batch-print'
    | '/contracts/'
    | '/admin/dashboard'
    | '/collections/$id'
    | '/collections/create'
    | '/groups/$id'
    | '/groups/create'
    | '/reservations/$id'
    | '/reservations/create'
    | '/resources/$id'
    | '/resources/create'
    | '/users/$id'
    | '/users/create'
    | '/calendar/'
    | '/collections/'
    | '/groups/'
    | '/reservations/'
    | '/resources/'
    | '/users/'
    | '/collections/edit/$id'
    | '/groups/edit/$id'
    | '/reservations/edit/$id'
    | '/resources/edit/$id'
    | '/users/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sandbox'
    | '/contracts/batch-print'
    | '/'
    | '/contracts'
    | '/admin/dashboard'
    | '/collections/$id'
    | '/collections/create'
    | '/groups/$id'
    | '/groups/create'
    | '/reservations/$id'
    | '/reservations/create'
    | '/resources/$id'
    | '/resources/create'
    | '/users/$id'
    | '/users/create'
    | '/calendar'
    | '/collections'
    | '/groups'
    | '/reservations'
    | '/resources'
    | '/users'
    | '/collections/edit/$id'
    | '/groups/edit/$id'
    | '/reservations/edit/$id'
    | '/resources/edit/$id'
    | '/users/edit/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/sandbox'
    | '/contracts/batch-print'
    | '/_app/'
    | '/contracts/'
    | '/_app/admin/dashboard'
    | '/_app/collections/$id'
    | '/_app/collections/create'
    | '/_app/groups/$id'
    | '/_app/groups/create'
    | '/_app/reservations/$id'
    | '/_app/reservations/create'
    | '/_app/resources/$id'
    | '/_app/resources/create'
    | '/_app/users/$id'
    | '/_app/users/create'
    | '/_app/calendar/'
    | '/_app/collections/'
    | '/_app/groups/'
    | '/_app/reservations/'
    | '/_app/resources/'
    | '/_app/users/'
    | '/_app/collections/edit/$id'
    | '/_app/groups/edit/$id'
    | '/_app/reservations/edit/$id'
    | '/_app/resources/edit/$id'
    | '/_app/users/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ContractsBatchPrintRoute: typeof ContractsBatchPrintRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sandbox': {
      id: '/_app/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof AppSandboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/batch-print': {
      id: '/contracts/batch-print'
      path: '/contracts/batch-print'
      fullPath: '/contracts/batch-print'
      preLoaderRoute: typeof ContractsBatchPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections/': {
      id: '/_app/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AppCollectionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections/$id': {
      id: '/_app/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AppCollectionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections/create': {
      id: '/_app/collections/create'
      path: '/collections/create'
      fullPath: '/collections/create'
      preLoaderRoute: typeof AppCollectionsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$id': {
      id: '/_app/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AppGroupsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/create': {
      id: '/_app/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AppGroupsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations/': {
      id: '/_app/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof AppReservationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations/$id': {
      id: '/_app/reservations/$id'
      path: '/reservations/$id'
      fullPath: '/reservations/$id'
      preLoaderRoute: typeof AppReservationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations/create': {
      id: '/_app/reservations/create'
      path: '/reservations/create'
      fullPath: '/reservations/create'
      preLoaderRoute: typeof AppReservationsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/': {
      id: '/_app/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof AppResourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/$id': {
      id: '/_app/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof AppResourcesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/create': {
      id: '/_app/resources/create'
      path: '/resources/create'
      fullPath: '/resources/create'
      preLoaderRoute: typeof AppResourcesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$id': {
      id: '/_app/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AppUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/create': {
      id: '/_app/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AppUsersCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections/edit/$id': {
      id: '/_app/collections/edit/$id'
      path: '/collections/edit/$id'
      fullPath: '/collections/edit/$id'
      preLoaderRoute: typeof AppCollectionsEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/edit/$id': {
      id: '/_app/groups/edit/$id'
      path: '/groups/edit/$id'
      fullPath: '/groups/edit/$id'
      preLoaderRoute: typeof AppGroupsEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations/edit/$id': {
      id: '/_app/reservations/edit/$id'
      path: '/reservations/edit/$id'
      fullPath: '/reservations/edit/$id'
      preLoaderRoute: typeof AppReservationsEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/edit/$id': {
      id: '/_app/resources/edit/$id'
      path: '/resources/edit/$id'
      fullPath: '/resources/edit/$id'
      preLoaderRoute: typeof AppResourcesEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/edit/$id': {
      id: '/_app/users/edit/$id'
      path: '/users/edit/$id'
      fullPath: '/users/edit/$id'
      preLoaderRoute: typeof AppUsersEditIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSandboxRoute: typeof AppSandboxRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppCollectionsIdRoute: typeof AppCollectionsIdRoute
  AppCollectionsCreateRoute: typeof AppCollectionsCreateRoute
  AppGroupsIdRoute: typeof AppGroupsIdRoute
  AppGroupsCreateRoute: typeof AppGroupsCreateRoute
  AppReservationsIdRoute: typeof AppReservationsIdRoute
  AppReservationsCreateRoute: typeof AppReservationsCreateRoute
  AppResourcesIdRoute: typeof AppResourcesIdRoute
  AppResourcesCreateRoute: typeof AppResourcesCreateRoute
  AppUsersIdRoute: typeof AppUsersIdRoute
  AppUsersCreateRoute: typeof AppUsersCreateRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppCollectionsIndexRoute: typeof AppCollectionsIndexRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppReservationsIndexRoute: typeof AppReservationsIndexRoute
  AppResourcesIndexRoute: typeof AppResourcesIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppCollectionsEditIdRoute: typeof AppCollectionsEditIdRoute
  AppGroupsEditIdRoute: typeof AppGroupsEditIdRoute
  AppReservationsEditIdRoute: typeof AppReservationsEditIdRoute
  AppResourcesEditIdRoute: typeof AppResourcesEditIdRoute
  AppUsersEditIdRoute: typeof AppUsersEditIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSandboxRoute: AppSandboxRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppCollectionsIdRoute: AppCollectionsIdRoute,
  AppCollectionsCreateRoute: AppCollectionsCreateRoute,
  AppGroupsIdRoute: AppGroupsIdRoute,
  AppGroupsCreateRoute: AppGroupsCreateRoute,
  AppReservationsIdRoute: AppReservationsIdRoute,
  AppReservationsCreateRoute: AppReservationsCreateRoute,
  AppResourcesIdRoute: AppResourcesIdRoute,
  AppResourcesCreateRoute: AppResourcesCreateRoute,
  AppUsersIdRoute: AppUsersIdRoute,
  AppUsersCreateRoute: AppUsersCreateRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppCollectionsIndexRoute: AppCollectionsIndexRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppReservationsIndexRoute: AppReservationsIndexRoute,
  AppResourcesIndexRoute: AppResourcesIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppCollectionsEditIdRoute: AppCollectionsEditIdRoute,
  AppGroupsEditIdRoute: AppGroupsEditIdRoute,
  AppReservationsEditIdRoute: AppReservationsEditIdRoute,
  AppResourcesEditIdRoute: AppResourcesEditIdRoute,
  AppUsersEditIdRoute: AppUsersEditIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ContractsBatchPrintRoute: ContractsBatchPrintRoute,
  ContractsIndexRoute: ContractsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
